// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParksLookupApi.Models;

#nullable disable

namespace ParksLookup.Migrations
{
    [DbContext(typeof(ParksLookupApiContext))]
    partial class ParksLookupApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ParksLookupApi.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("FeaturedAnimal")
                        .HasColumnType("longtext");

                    b.Property<int>("InceptionYear")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("State")
                        .HasColumnType("longtext");

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            FeaturedAnimal = "Elk",
                            InceptionYear = 1872,
                            Name = "Yellowstone",
                            State = "Wyoming"
                        },
                        new
                        {
                            ParkId = 2,
                            FeaturedAnimal = "Golden-Mantled Ground Squirrel",
                            InceptionYear = 1902,
                            Name = "Crater Lake",
                            State = "Oregon"
                        },
                        new
                        {
                            ParkId = 3,
                            FeaturedAnimal = "Desert Bighorn Sheep",
                            InceptionYear = 1964,
                            Name = "Canyonlands",
                            State = "Utah"
                        },
                        new
                        {
                            ParkId = 4,
                            FeaturedAnimal = "Great Horned Owl",
                            InceptionYear = 1958,
                            Name = "Oswald West State Park",
                            State = "Oregon"
                        },
                        new
                        {
                            ParkId = 5,
                            FeaturedAnimal = "Red-Shouldered Hawks",
                            InceptionYear = 1929,
                            Name = "Fahnestock",
                            State = "New York"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
